package SicsWsPcAccountingEntryPoint;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.1.8
//
// Created by Quasar Development at 30/01/2017
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class LightClaimSocToClaimRelationship extends DomainObject implements KvmSerializable,java.io.Serializable
{

    
	/**
	* SubclassNumber: 517. SicsRefClaimStatus
	*/
    public SicsReferenceDataReference claimStatus;
    
	/**
	* SubclassNumber: 518. SicsRefClaimSubStatus
	*/
    public SicsReferenceDataReference claimSubStatus;
    
    public String claimantName;
    
    public java.util.Date claimAdvisedDate;
    
    public AdviceMonetaryAmount adviceAmountCurrency;
    
    public String claimOriginalPolicyId;

    public LightClaimSocToClaimRelationship ()
    {
    }

    public LightClaimSocToClaimRelationship (java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
	    super(paramObj, __envelope);
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                java.lang.Object obj = info.getValue(); 
                if (info.name.equals("claimStatus"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.claimStatus = (SicsReferenceDataReference)__envelope.get(j,SicsReferenceDataReference.class,false);
                    }
                    continue;
                }
                if (info.name.equals("claimSubStatus"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.claimSubStatus = (SicsReferenceDataReference)__envelope.get(j,SicsReferenceDataReference.class,false);
                    }
                    continue;
                }
                if (info.name.equals("claimantName"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.claimantName = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.claimantName = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("claimAdvisedDate"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.claimAdvisedDate = Helper.ConvertFromWebService(j.toString());
                            }
                        }
                        else if (obj instanceof java.util.Date){
                            this.claimAdvisedDate = (java.util.Date)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("adviceAmountCurrency"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.adviceAmountCurrency = (AdviceMonetaryAmount)__envelope.get(j,AdviceMonetaryAmount.class,false);
                    }
                    continue;
                }
                if (info.name.equals("claimOriginalPolicyId"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.claimOriginalPolicyId = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.claimOriginalPolicyId = (String)obj;
                        }
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==count+0)
        {
            return this.claimStatus!=null?this.claimStatus:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+1)
        {
            return this.claimSubStatus!=null?this.claimSubStatus:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+2)
        {
            return this.claimantName!=null?this.claimantName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+3)
        {
            return this.claimAdvisedDate!=null?Helper.getDateFormat().format(this.claimAdvisedDate):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+4)
        {
            return this.adviceAmountCurrency!=null?this.adviceAmountCurrency:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+5)
        {
            return this.claimOriginalPolicyId!=null?this.claimOriginalPolicyId:SoapPrimitive.NullSkip;
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+6;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        int count = super.getPropertyCount();
        if(propertyIndex==count+0)
        {
            info.type = SicsReferenceDataReference.class;
            info.name = "claimStatus";
            info.namespace= "";
        }
        if(propertyIndex==count+1)
        {
            info.type = SicsReferenceDataReference.class;
            info.name = "claimSubStatus";
            info.namespace= "";
        }
        if(propertyIndex==count+2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "claimantName";
            info.namespace= "";
        }
        if(propertyIndex==count+3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "claimAdvisedDate";
            info.namespace= "";
        }
        if(propertyIndex==count+4)
        {
            info.type = AdviceMonetaryAmount.class;
            info.name = "adviceAmountCurrency";
            info.namespace= "";
        }
        if(propertyIndex==count+5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "claimOriginalPolicyId";
            info.namespace= "";
        }
        super.getPropertyInfo(propertyIndex,arg1,info);
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

