package ips;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.1.8
//
// Created by Quasar Development at 29/01/2017
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class ClaimGroupUpdate extends AttributeContainer implements KvmSerializable,java.io.Serializable
{

    
	/**
	* SubclassNumber: 519.
	*/
    public SicsReferenceDataReference claimGroupCategory;
    
    public String name;
    
    public Boolean isActive;
    
    public ClaimClaimGroupRelationshipList claimGroupRelationshipList;
    
    public ClaimSignatureNoteList claimSignatureNoteList;
    
    public ClaimClaimGroupRelationshipListUpdate claimGroupRelationshipListUpdate;
    
    public ClaimSignatureNoteListUpdate claimSignatureNoteListUpdate;

    public ClaimGroupUpdate ()
    {
    }

    public ClaimGroupUpdate (java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                java.lang.Object obj = info.getValue(); 
                if (info.name.equals("claimGroupCategory"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.claimGroupCategory = (SicsReferenceDataReference)__envelope.get(j,SicsReferenceDataReference.class,false);
                    }
                    continue;
                }
                if (info.name.equals("name"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.name = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.name = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("isActive"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.isActive = new Boolean(j.toString());
                            }
                        }
                        else if (obj instanceof Boolean){
                            this.isActive = (Boolean)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("claimGroupRelationshipList"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.claimGroupRelationshipList = new ClaimClaimGroupRelationshipList(j,__envelope);
                    }
                    continue;
                }
                if (info.name.equals("claimSignatureNoteList"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.claimSignatureNoteList = new ClaimSignatureNoteList(j,__envelope);
                    }
                    continue;
                }
                if (info.name.equals("claimGroupRelationshipListUpdate"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.claimGroupRelationshipListUpdate = (ClaimClaimGroupRelationshipListUpdate)__envelope.get(j,ClaimClaimGroupRelationshipListUpdate.class,false);
                    }
                    continue;
                }
                if (info.name.equals("claimSignatureNoteListUpdate"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.claimSignatureNoteListUpdate = (ClaimSignatureNoteListUpdate)__envelope.get(j,ClaimSignatureNoteListUpdate.class,false);
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.claimGroupCategory!=null?this.claimGroupCategory:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.name!=null?this.name:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.isActive!=null?this.isActive:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.claimGroupRelationshipList!=null?this.claimGroupRelationshipList:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.claimSignatureNoteList!=null?this.claimSignatureNoteList:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.claimGroupRelationshipListUpdate!=null?this.claimGroupRelationshipListUpdate:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.claimSignatureNoteListUpdate!=null?this.claimSignatureNoteListUpdate:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 7;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = SicsReferenceDataReference.class;
            info.name = "claimGroupCategory";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "name";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "isActive";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "claimGroupRelationshipList";
            info.namespace= "";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "claimSignatureNoteList";
            info.namespace= "";
        }
        if(propertyIndex==5)
        {
            info.type = ClaimClaimGroupRelationshipListUpdate.class;
            info.name = "claimGroupRelationshipListUpdate";
            info.namespace= "";
        }
        if(propertyIndex==6)
        {
            info.type = ClaimSignatureNoteListUpdate.class;
            info.name = "claimSignatureNoteListUpdate";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

