package ips;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.1.8
//
// Created by Quasar Development at 29/01/2017
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class CreateScopeOfCoverInput extends AttributeContainer implements KvmSerializable,java.io.Serializable
{

    
	/**
	* will calculate exposure from limit/premium condition; and ourExposure from exposure *share    (unless ourExposure is specified)
	*/
    public Boolean calculateExposure;
    
	/**
	* The parent for the child I create.
	*/
    public SicsScopeOfCoverReference parentScopeOfCover;
    
    public ScopeOfCover childScopeOfCover;
    
    public CessionDeclarationScopeOfCover childDeclaration;
    
    public CessionInsurableObjectScopeOfCover childCession;

    public CreateScopeOfCoverInput ()
    {
    }

    public CreateScopeOfCoverInput (java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                java.lang.Object obj = info.getValue(); 
                if (info.name.equals("calculateExposure"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.calculateExposure = new Boolean(j.toString());
                            }
                        }
                        else if (obj instanceof Boolean){
                            this.calculateExposure = (Boolean)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("parentScopeOfCover"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.parentScopeOfCover = (SicsScopeOfCoverReference)__envelope.get(j,SicsScopeOfCoverReference.class,false);
                    }
                    continue;
                }
                if (info.name.equals("childScopeOfCover"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.childScopeOfCover = (ScopeOfCover)__envelope.get(j,ScopeOfCover.class,false);
                    }
                    continue;
                }
                if (info.name.equals("childDeclaration"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.childDeclaration = (CessionDeclarationScopeOfCover)__envelope.get(j,CessionDeclarationScopeOfCover.class,false);
                    }
                    continue;
                }
                if (info.name.equals("childCession"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.childCession = (CessionInsurableObjectScopeOfCover)__envelope.get(j,CessionInsurableObjectScopeOfCover.class,false);
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.calculateExposure!=null?this.calculateExposure:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return parentScopeOfCover;
        }
        if(propertyIndex==2)
        {
            return this.childScopeOfCover!=null?this.childScopeOfCover:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.childDeclaration!=null?this.childDeclaration:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.childCession!=null?this.childCession:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 5;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "calculateExposure";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = SicsScopeOfCoverReference.class;
            info.name = "parentScopeOfCover";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = ScopeOfCover.class;
            info.name = "childScopeOfCover";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = CessionDeclarationScopeOfCover.class;
            info.name = "childDeclaration";
            info.namespace= "";
        }
        if(propertyIndex==4)
        {
            info.type = CessionInsurableObjectScopeOfCover.class;
            info.name = "childCession";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

