package SicsWsDomainSearchEntryPoint;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.1.8
//
// Created by Quasar Development at 29/01/2017
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.math.BigDecimal;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public class AbstractCessionDeclarationScopeOfCover extends AbstractScopeOfCover implements KvmSerializable,java.io.Serializable
{

    
    public java.util.Date attachmentFromDate;
    
    public java.util.Date attachmentToDate;
    
	/**
	* CededShare element is absolute now. Pl ignore this variable
	*/
    public BigDecimal cededShare;
    
    public ArrayList< SicsBusinessPartnerReference> cessionInsured =new ArrayList<SicsBusinessPartnerReference >();
    
    public String cessionNote;
    
    public String declarationNumber;
    
    public BigDecimal exposure;
    
    public String originalPolicyId;
    
    public BigDecimal ourExposure=BigDecimal.ZERO;
    
    public Boolean isSpecialAcceptance=false;
    
	/**
	* SubclassNumber: 01071.
	*/
    public SicsReferenceDataReference reasonForSpecialAcceptance;

    public AbstractCessionDeclarationScopeOfCover ()
    {
    }

    public AbstractCessionDeclarationScopeOfCover (java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
	    super(paramObj, __envelope);
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                java.lang.Object obj = info.getValue(); 
                if (info.name.equals("attachmentFromDate"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.attachmentFromDate = Helper.ConvertFromWebService(j.toString());
                            }
                        }
                        else if (obj instanceof java.util.Date){
                            this.attachmentFromDate = (java.util.Date)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("attachmentToDate"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.attachmentToDate = Helper.ConvertFromWebService(j.toString());
                            }
                        }
                        else if (obj instanceof java.util.Date){
                            this.attachmentToDate = (java.util.Date)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("cededShare"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.cededShare = new BigDecimal(j.toString());
                            }
                        }
                        else if (obj instanceof BigDecimal){
                            this.cededShare = (BigDecimal)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("cessionInsured"))
                {
                    if(obj!=null)
                    {
        
                    
                        if(this.cessionInsured==null)
                        {
                            this.cessionInsured = new ArrayList< SicsBusinessPartnerReference>();
                        }
                        java.lang.Object j =obj;
                        SicsBusinessPartnerReference j1= (SicsBusinessPartnerReference)__envelope.get(j,SicsBusinessPartnerReference.class,false);
                        this.cessionInsured.add(j1);
                   
        
                    }
                    continue;
                }
                if (info.name.equals("cessionNote"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.cessionNote = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.cessionNote = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("declarationNumber"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.declarationNumber = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.declarationNumber = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("exposure"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.exposure = new BigDecimal(j.toString());
                            }
                        }
                        else if (obj instanceof BigDecimal){
                            this.exposure = (BigDecimal)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("originalPolicyId"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.originalPolicyId = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.originalPolicyId = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("ourExposure"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.ourExposure = new BigDecimal(j.toString());
                            }
                        }
                        else if (obj instanceof BigDecimal){
                            this.ourExposure = (BigDecimal)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("isSpecialAcceptance"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.isSpecialAcceptance = new Boolean(j.toString());
                            }
                        }
                        else if (obj instanceof Boolean){
                            this.isSpecialAcceptance = (Boolean)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("reasonForSpecialAcceptance"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.reasonForSpecialAcceptance = (SicsReferenceDataReference)__envelope.get(j,SicsReferenceDataReference.class,false);
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==count+0)
        {
            return this.attachmentFromDate!=null?Helper.getDateFormat().format(this.attachmentFromDate):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+1)
        {
            return this.attachmentToDate!=null?Helper.getDateFormat().format(this.attachmentToDate):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+2)
        {
            return this.cededShare!=null?this.cededShare.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex>=count+3 && propertyIndex < count+3+this.cessionInsured.size())
        {
            return this.cessionInsured.get(propertyIndex-(count+3));
        }
        if(propertyIndex==count+3+this.cessionInsured.size())
        {
            return this.cessionNote!=null?this.cessionNote:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==count+4+this.cessionInsured.size())
        {
            return this.declarationNumber!=null?this.declarationNumber:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+5+this.cessionInsured.size())
        {
            return this.exposure!=null?this.exposure.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+6+this.cessionInsured.size())
        {
            return this.originalPolicyId!=null?this.originalPolicyId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+7+this.cessionInsured.size())
        {
            return this.ourExposure!=null?this.ourExposure.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+8+this.cessionInsured.size())
        {
            return isSpecialAcceptance;
        }
        if(propertyIndex==count+9+this.cessionInsured.size())
        {
            return reasonForSpecialAcceptance;
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+10+cessionInsured.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        int count = super.getPropertyCount();
        if(propertyIndex==count+0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "attachmentFromDate";
            info.namespace= "";
        }
        if(propertyIndex==count+1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "attachmentToDate";
            info.namespace= "";
        }
        if(propertyIndex==count+2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "cededShare";
            info.namespace= "";
        }
        if(propertyIndex>=count+3 && propertyIndex < count+3+this.cessionInsured.size())
        {
            info.type = SicsBusinessPartnerReference.class;
            info.name = "cessionInsured";
            info.namespace= "";
        }
        if(propertyIndex==count+3+this.cessionInsured.size())
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "cessionNote";
            info.namespace= "";
        }
        if(propertyIndex==count+4+this.cessionInsured.size())
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "declarationNumber";
            info.namespace= "";
        }
        if(propertyIndex==count+5+this.cessionInsured.size())
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "exposure";
            info.namespace= "";
        }
        if(propertyIndex==count+6+this.cessionInsured.size())
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "originalPolicyId";
            info.namespace= "";
        }
        if(propertyIndex==count+7+this.cessionInsured.size())
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ourExposure";
            info.namespace= "";
        }
        if(propertyIndex==count+8+this.cessionInsured.size())
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "isSpecialAcceptance";
            info.namespace= "";
        }
        if(propertyIndex==count+9+this.cessionInsured.size())
        {
            info.type = SicsReferenceDataReference.class;
            info.name = "reasonForSpecialAcceptance";
            info.namespace= "";
        }
        super.getPropertyInfo(propertyIndex,arg1,info);
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

