package SicsWsDomainSearchEntryPoint;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.1.8
//
// Created by Quasar Development at 29/01/2017
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.math.BigDecimal;

public class UserDefinedFields extends DomainObject implements KvmSerializable,java.io.Serializable
{

    
    public String string01;
    
    public String string02;
    
    public String string03;
    
    public String string04;
    
    public String string05;
    
	/**
	* Can contain any Reference Data SUBCLASS/CODE, according to the Reference Data Type defined in the user defined fields maintenance window.
	*/
    public SicsReferenceDataReference refData01;
    
    public SicsReferenceDataReference refData02;
    
    public SicsReferenceDataReference refData03;
    
    public SicsReferenceDataReference refData04;
    
    public SicsReferenceDataReference refData05;
    
    public SicsReferenceDataReference refData06;
    
    public SicsReferenceDataReference refData07;
    
    public SicsReferenceDataReference refData08;
    
    public SicsReferenceDataReference refData09;
    
    public SicsReferenceDataReference refData10;
    
    public SicsReferenceDataReference refData11;
    
    public SicsReferenceDataReference refData12;
    
    public SicsReferenceDataReference refData13;
    
    public SicsReferenceDataReference refData14;
    
    public SicsReferenceDataReference refData15;
    
    public SicsCurrencyReference currency01;
    
    public SicsCurrencyReference currency02;
    
    public SicsCurrencyReference currency03;
    
    public SicsCurrencyReference currency04;
    
    public SicsCurrencyReference currency05;
    
    public java.util.Date date01;
    
    public java.util.Date date02;
    
    public java.util.Date date03;
    
    public java.util.Date date04;
    
    public java.util.Date date05;
    
    public BigDecimal percent01;
    
    public BigDecimal percent02;
    
    public BigDecimal percent03;
    
    public BigDecimal percent04;
    
    public BigDecimal percent05;
    
    public BigDecimal percent06;
    
    public BigDecimal percent07;
    
    public BigDecimal percent08;
    
    public BigDecimal percent09;
    
    public BigDecimal percent10;
    
    public BigDecimal decimal01;
    
    public BigDecimal decimal02;
    
    public BigDecimal decimal03;
    
    public BigDecimal decimal04;
    
    public BigDecimal decimal05;
    
    public BigDecimal decimal06;
    
    public BigDecimal decimal07;
    
    public BigDecimal decimal08;
    
    public BigDecimal decimal09;
    
    public BigDecimal decimal10;
    
    public Long integer01;
    
    public Long integer02;
    
    public Long integer03;
    
    public Long integer04;
    
    public Long integer05;
    
    public Long integer06;
    
    public Long integer07;
    
    public Long integer08;
    
    public Long integer09;
    
    public Long integer10;
    
    public Boolean boolean01;
    
    public Boolean boolean02;
    
    public Boolean boolean03;
    
    public Boolean boolean04;
    
    public Boolean boolean05;
    
    public SicsMonetaryAmountReference monetaryAmount01;
    
    public SicsMonetaryAmountReference monetaryAmount02;
    
    public SicsMonetaryAmountReference monetaryAmount03;
    
    public SicsMonetaryAmountReference monetaryAmount04;
    
    public SicsMonetaryAmountReference monetaryAmount05;

    public UserDefinedFields ()
    {
    }

    public UserDefinedFields (java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
	    super(paramObj, __envelope);
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                java.lang.Object obj = info.getValue(); 
                if (info.name.equals("string01"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.string01 = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.string01 = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("string02"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.string02 = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.string02 = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("string03"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.string03 = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.string03 = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("string04"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.string04 = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.string04 = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("string05"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.string05 = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.string05 = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("refData01"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.refData01 = (SicsReferenceDataReference)__envelope.get(j,SicsReferenceDataReference.class,false);
                    }
                    continue;
                }
                if (info.name.equals("refData02"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.refData02 = (SicsReferenceDataReference)__envelope.get(j,SicsReferenceDataReference.class,false);
                    }
                    continue;
                }
                if (info.name.equals("refData03"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.refData03 = (SicsReferenceDataReference)__envelope.get(j,SicsReferenceDataReference.class,false);
                    }
                    continue;
                }
                if (info.name.equals("refData04"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.refData04 = (SicsReferenceDataReference)__envelope.get(j,SicsReferenceDataReference.class,false);
                    }
                    continue;
                }
                if (info.name.equals("refData05"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.refData05 = (SicsReferenceDataReference)__envelope.get(j,SicsReferenceDataReference.class,false);
                    }
                    continue;
                }
                if (info.name.equals("refData06"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.refData06 = (SicsReferenceDataReference)__envelope.get(j,SicsReferenceDataReference.class,false);
                    }
                    continue;
                }
                if (info.name.equals("refData07"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.refData07 = (SicsReferenceDataReference)__envelope.get(j,SicsReferenceDataReference.class,false);
                    }
                    continue;
                }
                if (info.name.equals("refData08"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.refData08 = (SicsReferenceDataReference)__envelope.get(j,SicsReferenceDataReference.class,false);
                    }
                    continue;
                }
                if (info.name.equals("refData09"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.refData09 = (SicsReferenceDataReference)__envelope.get(j,SicsReferenceDataReference.class,false);
                    }
                    continue;
                }
                if (info.name.equals("refData10"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.refData10 = (SicsReferenceDataReference)__envelope.get(j,SicsReferenceDataReference.class,false);
                    }
                    continue;
                }
                if (info.name.equals("refData11"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.refData11 = (SicsReferenceDataReference)__envelope.get(j,SicsReferenceDataReference.class,false);
                    }
                    continue;
                }
                if (info.name.equals("refData12"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.refData12 = (SicsReferenceDataReference)__envelope.get(j,SicsReferenceDataReference.class,false);
                    }
                    continue;
                }
                if (info.name.equals("refData13"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.refData13 = (SicsReferenceDataReference)__envelope.get(j,SicsReferenceDataReference.class,false);
                    }
                    continue;
                }
                if (info.name.equals("refData14"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.refData14 = (SicsReferenceDataReference)__envelope.get(j,SicsReferenceDataReference.class,false);
                    }
                    continue;
                }
                if (info.name.equals("refData15"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.refData15 = (SicsReferenceDataReference)__envelope.get(j,SicsReferenceDataReference.class,false);
                    }
                    continue;
                }
                if (info.name.equals("currency01"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.currency01 = (SicsCurrencyReference)__envelope.get(j,SicsCurrencyReference.class,false);
                    }
                    continue;
                }
                if (info.name.equals("currency02"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.currency02 = (SicsCurrencyReference)__envelope.get(j,SicsCurrencyReference.class,false);
                    }
                    continue;
                }
                if (info.name.equals("currency03"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.currency03 = (SicsCurrencyReference)__envelope.get(j,SicsCurrencyReference.class,false);
                    }
                    continue;
                }
                if (info.name.equals("currency04"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.currency04 = (SicsCurrencyReference)__envelope.get(j,SicsCurrencyReference.class,false);
                    }
                    continue;
                }
                if (info.name.equals("currency05"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.currency05 = (SicsCurrencyReference)__envelope.get(j,SicsCurrencyReference.class,false);
                    }
                    continue;
                }
                if (info.name.equals("date01"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.date01 = Helper.ConvertFromWebService(j.toString());
                            }
                        }
                        else if (obj instanceof java.util.Date){
                            this.date01 = (java.util.Date)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("date02"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.date02 = Helper.ConvertFromWebService(j.toString());
                            }
                        }
                        else if (obj instanceof java.util.Date){
                            this.date02 = (java.util.Date)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("date03"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.date03 = Helper.ConvertFromWebService(j.toString());
                            }
                        }
                        else if (obj instanceof java.util.Date){
                            this.date03 = (java.util.Date)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("date04"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.date04 = Helper.ConvertFromWebService(j.toString());
                            }
                        }
                        else if (obj instanceof java.util.Date){
                            this.date04 = (java.util.Date)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("date05"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.date05 = Helper.ConvertFromWebService(j.toString());
                            }
                        }
                        else if (obj instanceof java.util.Date){
                            this.date05 = (java.util.Date)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("percent01"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.percent01 = new BigDecimal(j.toString());
                            }
                        }
                        else if (obj instanceof BigDecimal){
                            this.percent01 = (BigDecimal)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("percent02"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.percent02 = new BigDecimal(j.toString());
                            }
                        }
                        else if (obj instanceof BigDecimal){
                            this.percent02 = (BigDecimal)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("percent03"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.percent03 = new BigDecimal(j.toString());
                            }
                        }
                        else if (obj instanceof BigDecimal){
                            this.percent03 = (BigDecimal)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("percent04"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.percent04 = new BigDecimal(j.toString());
                            }
                        }
                        else if (obj instanceof BigDecimal){
                            this.percent04 = (BigDecimal)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("percent05"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.percent05 = new BigDecimal(j.toString());
                            }
                        }
                        else if (obj instanceof BigDecimal){
                            this.percent05 = (BigDecimal)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("percent06"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.percent06 = new BigDecimal(j.toString());
                            }
                        }
                        else if (obj instanceof BigDecimal){
                            this.percent06 = (BigDecimal)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("percent07"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.percent07 = new BigDecimal(j.toString());
                            }
                        }
                        else if (obj instanceof BigDecimal){
                            this.percent07 = (BigDecimal)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("percent08"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.percent08 = new BigDecimal(j.toString());
                            }
                        }
                        else if (obj instanceof BigDecimal){
                            this.percent08 = (BigDecimal)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("percent09"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.percent09 = new BigDecimal(j.toString());
                            }
                        }
                        else if (obj instanceof BigDecimal){
                            this.percent09 = (BigDecimal)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("percent10"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.percent10 = new BigDecimal(j.toString());
                            }
                        }
                        else if (obj instanceof BigDecimal){
                            this.percent10 = (BigDecimal)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("decimal01"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.decimal01 = new BigDecimal(j.toString());
                            }
                        }
                        else if (obj instanceof BigDecimal){
                            this.decimal01 = (BigDecimal)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("decimal02"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.decimal02 = new BigDecimal(j.toString());
                            }
                        }
                        else if (obj instanceof BigDecimal){
                            this.decimal02 = (BigDecimal)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("decimal03"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.decimal03 = new BigDecimal(j.toString());
                            }
                        }
                        else if (obj instanceof BigDecimal){
                            this.decimal03 = (BigDecimal)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("decimal04"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.decimal04 = new BigDecimal(j.toString());
                            }
                        }
                        else if (obj instanceof BigDecimal){
                            this.decimal04 = (BigDecimal)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("decimal05"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.decimal05 = new BigDecimal(j.toString());
                            }
                        }
                        else if (obj instanceof BigDecimal){
                            this.decimal05 = (BigDecimal)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("decimal06"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.decimal06 = new BigDecimal(j.toString());
                            }
                        }
                        else if (obj instanceof BigDecimal){
                            this.decimal06 = (BigDecimal)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("decimal07"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.decimal07 = new BigDecimal(j.toString());
                            }
                        }
                        else if (obj instanceof BigDecimal){
                            this.decimal07 = (BigDecimal)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("decimal08"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.decimal08 = new BigDecimal(j.toString());
                            }
                        }
                        else if (obj instanceof BigDecimal){
                            this.decimal08 = (BigDecimal)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("decimal09"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.decimal09 = new BigDecimal(j.toString());
                            }
                        }
                        else if (obj instanceof BigDecimal){
                            this.decimal09 = (BigDecimal)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("decimal10"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.decimal10 = new BigDecimal(j.toString());
                            }
                        }
                        else if (obj instanceof BigDecimal){
                            this.decimal10 = (BigDecimal)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("integer01"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.integer01 = new Long(j.toString());
                            }
                        }
                        else if (obj instanceof Long){
                            this.integer01 = (Long)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("integer02"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.integer02 = new Long(j.toString());
                            }
                        }
                        else if (obj instanceof Long){
                            this.integer02 = (Long)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("integer03"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.integer03 = new Long(j.toString());
                            }
                        }
                        else if (obj instanceof Long){
                            this.integer03 = (Long)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("integer04"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.integer04 = new Long(j.toString());
                            }
                        }
                        else if (obj instanceof Long){
                            this.integer04 = (Long)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("integer05"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.integer05 = new Long(j.toString());
                            }
                        }
                        else if (obj instanceof Long){
                            this.integer05 = (Long)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("integer06"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.integer06 = new Long(j.toString());
                            }
                        }
                        else if (obj instanceof Long){
                            this.integer06 = (Long)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("integer07"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.integer07 = new Long(j.toString());
                            }
                        }
                        else if (obj instanceof Long){
                            this.integer07 = (Long)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("integer08"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.integer08 = new Long(j.toString());
                            }
                        }
                        else if (obj instanceof Long){
                            this.integer08 = (Long)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("integer09"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.integer09 = new Long(j.toString());
                            }
                        }
                        else if (obj instanceof Long){
                            this.integer09 = (Long)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("integer10"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.integer10 = new Long(j.toString());
                            }
                        }
                        else if (obj instanceof Long){
                            this.integer10 = (Long)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("boolean01"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.boolean01 = new Boolean(j.toString());
                            }
                        }
                        else if (obj instanceof Boolean){
                            this.boolean01 = (Boolean)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("boolean02"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.boolean02 = new Boolean(j.toString());
                            }
                        }
                        else if (obj instanceof Boolean){
                            this.boolean02 = (Boolean)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("boolean03"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.boolean03 = new Boolean(j.toString());
                            }
                        }
                        else if (obj instanceof Boolean){
                            this.boolean03 = (Boolean)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("boolean04"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.boolean04 = new Boolean(j.toString());
                            }
                        }
                        else if (obj instanceof Boolean){
                            this.boolean04 = (Boolean)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("boolean05"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.boolean05 = new Boolean(j.toString());
                            }
                        }
                        else if (obj instanceof Boolean){
                            this.boolean05 = (Boolean)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("monetaryAmount01"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.monetaryAmount01 = (SicsMonetaryAmountReference)__envelope.get(j,SicsMonetaryAmountReference.class,false);
                    }
                    continue;
                }
                if (info.name.equals("monetaryAmount02"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.monetaryAmount02 = (SicsMonetaryAmountReference)__envelope.get(j,SicsMonetaryAmountReference.class,false);
                    }
                    continue;
                }
                if (info.name.equals("monetaryAmount03"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.monetaryAmount03 = (SicsMonetaryAmountReference)__envelope.get(j,SicsMonetaryAmountReference.class,false);
                    }
                    continue;
                }
                if (info.name.equals("monetaryAmount04"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.monetaryAmount04 = (SicsMonetaryAmountReference)__envelope.get(j,SicsMonetaryAmountReference.class,false);
                    }
                    continue;
                }
                if (info.name.equals("monetaryAmount05"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.monetaryAmount05 = (SicsMonetaryAmountReference)__envelope.get(j,SicsMonetaryAmountReference.class,false);
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==count+0)
        {
            return this.string01!=null?this.string01:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+1)
        {
            return this.string02!=null?this.string02:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+2)
        {
            return this.string03!=null?this.string03:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+3)
        {
            return this.string04!=null?this.string04:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+4)
        {
            return this.string05!=null?this.string05:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+5)
        {
            return this.refData01!=null?this.refData01:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+6)
        {
            return this.refData02!=null?this.refData02:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+7)
        {
            return this.refData03!=null?this.refData03:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+8)
        {
            return this.refData04!=null?this.refData04:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+9)
        {
            return this.refData05!=null?this.refData05:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+10)
        {
            return this.refData06!=null?this.refData06:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+11)
        {
            return this.refData07!=null?this.refData07:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+12)
        {
            return this.refData08!=null?this.refData08:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+13)
        {
            return this.refData09!=null?this.refData09:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+14)
        {
            return this.refData10!=null?this.refData10:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+15)
        {
            return this.refData11!=null?this.refData11:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+16)
        {
            return this.refData12!=null?this.refData12:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+17)
        {
            return this.refData13!=null?this.refData13:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+18)
        {
            return this.refData14!=null?this.refData14:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+19)
        {
            return this.refData15!=null?this.refData15:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+20)
        {
            return this.currency01!=null?this.currency01:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+21)
        {
            return this.currency02!=null?this.currency02:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+22)
        {
            return this.currency03!=null?this.currency03:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+23)
        {
            return this.currency04!=null?this.currency04:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+24)
        {
            return this.currency05!=null?this.currency05:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+25)
        {
            return this.date01!=null?Helper.getDateFormat().format(this.date01):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+26)
        {
            return this.date02!=null?Helper.getDateFormat().format(this.date02):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+27)
        {
            return this.date03!=null?Helper.getDateFormat().format(this.date03):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+28)
        {
            return this.date04!=null?Helper.getDateFormat().format(this.date04):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+29)
        {
            return this.date05!=null?Helper.getDateFormat().format(this.date05):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+30)
        {
            return this.percent01!=null?this.percent01.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+31)
        {
            return this.percent02!=null?this.percent02.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+32)
        {
            return this.percent03!=null?this.percent03.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+33)
        {
            return this.percent04!=null?this.percent04.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+34)
        {
            return this.percent05!=null?this.percent05.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+35)
        {
            return this.percent06!=null?this.percent06.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+36)
        {
            return this.percent07!=null?this.percent07.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+37)
        {
            return this.percent08!=null?this.percent08.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+38)
        {
            return this.percent09!=null?this.percent09.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+39)
        {
            return this.percent10!=null?this.percent10.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+40)
        {
            return this.decimal01!=null?this.decimal01.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+41)
        {
            return this.decimal02!=null?this.decimal02.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+42)
        {
            return this.decimal03!=null?this.decimal03.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+43)
        {
            return this.decimal04!=null?this.decimal04.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+44)
        {
            return this.decimal05!=null?this.decimal05.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+45)
        {
            return this.decimal06!=null?this.decimal06.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+46)
        {
            return this.decimal07!=null?this.decimal07.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+47)
        {
            return this.decimal08!=null?this.decimal08.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+48)
        {
            return this.decimal09!=null?this.decimal09.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+49)
        {
            return this.decimal10!=null?this.decimal10.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+50)
        {
            return this.integer01!=null?this.integer01:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+51)
        {
            return this.integer02!=null?this.integer02:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+52)
        {
            return this.integer03!=null?this.integer03:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+53)
        {
            return this.integer04!=null?this.integer04:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+54)
        {
            return this.integer05!=null?this.integer05:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+55)
        {
            return this.integer06!=null?this.integer06:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+56)
        {
            return this.integer07!=null?this.integer07:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+57)
        {
            return this.integer08!=null?this.integer08:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+58)
        {
            return this.integer09!=null?this.integer09:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+59)
        {
            return this.integer10!=null?this.integer10:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+60)
        {
            return this.boolean01!=null?this.boolean01:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+61)
        {
            return this.boolean02!=null?this.boolean02:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+62)
        {
            return this.boolean03!=null?this.boolean03:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+63)
        {
            return this.boolean04!=null?this.boolean04:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+64)
        {
            return this.boolean05!=null?this.boolean05:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+65)
        {
            return this.monetaryAmount01!=null?this.monetaryAmount01:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+66)
        {
            return this.monetaryAmount02!=null?this.monetaryAmount02:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+67)
        {
            return this.monetaryAmount03!=null?this.monetaryAmount03:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+68)
        {
            return this.monetaryAmount04!=null?this.monetaryAmount04:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+69)
        {
            return this.monetaryAmount05!=null?this.monetaryAmount05:SoapPrimitive.NullSkip;
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+70;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        int count = super.getPropertyCount();
        if(propertyIndex==count+0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "string01";
            info.namespace= "";
        }
        if(propertyIndex==count+1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "string02";
            info.namespace= "";
        }
        if(propertyIndex==count+2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "string03";
            info.namespace= "";
        }
        if(propertyIndex==count+3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "string04";
            info.namespace= "";
        }
        if(propertyIndex==count+4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "string05";
            info.namespace= "";
        }
        if(propertyIndex==count+5)
        {
            info.type = SicsReferenceDataReference.class;
            info.name = "refData01";
            info.namespace= "";
        }
        if(propertyIndex==count+6)
        {
            info.type = SicsReferenceDataReference.class;
            info.name = "refData02";
            info.namespace= "";
        }
        if(propertyIndex==count+7)
        {
            info.type = SicsReferenceDataReference.class;
            info.name = "refData03";
            info.namespace= "";
        }
        if(propertyIndex==count+8)
        {
            info.type = SicsReferenceDataReference.class;
            info.name = "refData04";
            info.namespace= "";
        }
        if(propertyIndex==count+9)
        {
            info.type = SicsReferenceDataReference.class;
            info.name = "refData05";
            info.namespace= "";
        }
        if(propertyIndex==count+10)
        {
            info.type = SicsReferenceDataReference.class;
            info.name = "refData06";
            info.namespace= "";
        }
        if(propertyIndex==count+11)
        {
            info.type = SicsReferenceDataReference.class;
            info.name = "refData07";
            info.namespace= "";
        }
        if(propertyIndex==count+12)
        {
            info.type = SicsReferenceDataReference.class;
            info.name = "refData08";
            info.namespace= "";
        }
        if(propertyIndex==count+13)
        {
            info.type = SicsReferenceDataReference.class;
            info.name = "refData09";
            info.namespace= "";
        }
        if(propertyIndex==count+14)
        {
            info.type = SicsReferenceDataReference.class;
            info.name = "refData10";
            info.namespace= "";
        }
        if(propertyIndex==count+15)
        {
            info.type = SicsReferenceDataReference.class;
            info.name = "refData11";
            info.namespace= "";
        }
        if(propertyIndex==count+16)
        {
            info.type = SicsReferenceDataReference.class;
            info.name = "refData12";
            info.namespace= "";
        }
        if(propertyIndex==count+17)
        {
            info.type = SicsReferenceDataReference.class;
            info.name = "refData13";
            info.namespace= "";
        }
        if(propertyIndex==count+18)
        {
            info.type = SicsReferenceDataReference.class;
            info.name = "refData14";
            info.namespace= "";
        }
        if(propertyIndex==count+19)
        {
            info.type = SicsReferenceDataReference.class;
            info.name = "refData15";
            info.namespace= "";
        }
        if(propertyIndex==count+20)
        {
            info.type = SicsCurrencyReference.class;
            info.name = "currency01";
            info.namespace= "";
        }
        if(propertyIndex==count+21)
        {
            info.type = SicsCurrencyReference.class;
            info.name = "currency02";
            info.namespace= "";
        }
        if(propertyIndex==count+22)
        {
            info.type = SicsCurrencyReference.class;
            info.name = "currency03";
            info.namespace= "";
        }
        if(propertyIndex==count+23)
        {
            info.type = SicsCurrencyReference.class;
            info.name = "currency04";
            info.namespace= "";
        }
        if(propertyIndex==count+24)
        {
            info.type = SicsCurrencyReference.class;
            info.name = "currency05";
            info.namespace= "";
        }
        if(propertyIndex==count+25)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "date01";
            info.namespace= "";
        }
        if(propertyIndex==count+26)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "date02";
            info.namespace= "";
        }
        if(propertyIndex==count+27)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "date03";
            info.namespace= "";
        }
        if(propertyIndex==count+28)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "date04";
            info.namespace= "";
        }
        if(propertyIndex==count+29)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "date05";
            info.namespace= "";
        }
        if(propertyIndex==count+30)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "percent01";
            info.namespace= "";
        }
        if(propertyIndex==count+31)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "percent02";
            info.namespace= "";
        }
        if(propertyIndex==count+32)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "percent03";
            info.namespace= "";
        }
        if(propertyIndex==count+33)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "percent04";
            info.namespace= "";
        }
        if(propertyIndex==count+34)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "percent05";
            info.namespace= "";
        }
        if(propertyIndex==count+35)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "percent06";
            info.namespace= "";
        }
        if(propertyIndex==count+36)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "percent07";
            info.namespace= "";
        }
        if(propertyIndex==count+37)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "percent08";
            info.namespace= "";
        }
        if(propertyIndex==count+38)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "percent09";
            info.namespace= "";
        }
        if(propertyIndex==count+39)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "percent10";
            info.namespace= "";
        }
        if(propertyIndex==count+40)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "decimal01";
            info.namespace= "";
        }
        if(propertyIndex==count+41)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "decimal02";
            info.namespace= "";
        }
        if(propertyIndex==count+42)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "decimal03";
            info.namespace= "";
        }
        if(propertyIndex==count+43)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "decimal04";
            info.namespace= "";
        }
        if(propertyIndex==count+44)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "decimal05";
            info.namespace= "";
        }
        if(propertyIndex==count+45)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "decimal06";
            info.namespace= "";
        }
        if(propertyIndex==count+46)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "decimal07";
            info.namespace= "";
        }
        if(propertyIndex==count+47)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "decimal08";
            info.namespace= "";
        }
        if(propertyIndex==count+48)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "decimal09";
            info.namespace= "";
        }
        if(propertyIndex==count+49)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "decimal10";
            info.namespace= "";
        }
        if(propertyIndex==count+50)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "integer01";
            info.namespace= "";
        }
        if(propertyIndex==count+51)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "integer02";
            info.namespace= "";
        }
        if(propertyIndex==count+52)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "integer03";
            info.namespace= "";
        }
        if(propertyIndex==count+53)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "integer04";
            info.namespace= "";
        }
        if(propertyIndex==count+54)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "integer05";
            info.namespace= "";
        }
        if(propertyIndex==count+55)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "integer06";
            info.namespace= "";
        }
        if(propertyIndex==count+56)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "integer07";
            info.namespace= "";
        }
        if(propertyIndex==count+57)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "integer08";
            info.namespace= "";
        }
        if(propertyIndex==count+58)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "integer09";
            info.namespace= "";
        }
        if(propertyIndex==count+59)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "integer10";
            info.namespace= "";
        }
        if(propertyIndex==count+60)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "boolean01";
            info.namespace= "";
        }
        if(propertyIndex==count+61)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "boolean02";
            info.namespace= "";
        }
        if(propertyIndex==count+62)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "boolean03";
            info.namespace= "";
        }
        if(propertyIndex==count+63)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "boolean04";
            info.namespace= "";
        }
        if(propertyIndex==count+64)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "boolean05";
            info.namespace= "";
        }
        if(propertyIndex==count+65)
        {
            info.type = SicsMonetaryAmountReference.class;
            info.name = "monetaryAmount01";
            info.namespace= "";
        }
        if(propertyIndex==count+66)
        {
            info.type = SicsMonetaryAmountReference.class;
            info.name = "monetaryAmount02";
            info.namespace= "";
        }
        if(propertyIndex==count+67)
        {
            info.type = SicsMonetaryAmountReference.class;
            info.name = "monetaryAmount03";
            info.namespace= "";
        }
        if(propertyIndex==count+68)
        {
            info.type = SicsMonetaryAmountReference.class;
            info.name = "monetaryAmount04";
            info.namespace= "";
        }
        if(propertyIndex==count+69)
        {
            info.type = SicsMonetaryAmountReference.class;
            info.name = "monetaryAmount05";
            info.namespace= "";
        }
        super.getPropertyInfo(propertyIndex,arg1,info);
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

